### ISSUE TITLE
Does the plugin work with Hyper 3?

### ISSUE THREAD

**Issue by AntonioRedondo** [aurelienbottazini/hyperterm-crosshair#2]
I just installed this plugin in a fresh Hyper 3.0.2 and seems not to work. The plugin hasn't been updated in more than three years. So I guess it needs some update to make it work in the last version of Hyper?

**Comment by aurelienbottazini** [comment]
Sorry it does not work with Hyper version 3
Indeed they changed the rendering mechanism and it broke the plugin.

I don't use hyper term anymore so I don't plan to update the plugin anytime soon
